# These are supported funding model platforms

github: borkdude # [borkdude] # I joined the waiting list, but so far no response
patreon: borkdude
open_collective: # clj-kondo # Replace with a single Open Collective username
ko_fi: borkdude
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
